### ISSUE TITLE
Has this plugin been release anywhere?

### ISSUE THREAD

**Issue by hugocf** [rubendg/sbt-docker-label-schema#1]
Usage instructions need a version and it doesn’t seem to exist any such version on Bintray:
https://bintray.com/rubendg/sbt-plugins/sbt-docker-label-schema

```
addSbtPlugin("nl.rubendegooijer" % "sbt-docker-label-schema" % "")
```

Has it been released some place else? Or is it still no suitable to be used?

**Comment by rubendg** [comment]
Hi @hugocf thank you for your interest. I simply haven't found the time to hit the proverbial nail on the head. I'll have a look ASAP to at least publish what is here currently.

**Comment by hugocf** [comment]
That would be great! Thanks a lot

**Comment by rubendg** [comment]
@hugocf you can now give 0.1.0 a try ;)

**Comment by hugocf** [comment]
Many thanks. I managed to download and use it but I had to tweak the `resolvers` setting a bit to make it work.

The correct download url from Bintray has this format (notice the `.../nl.rubendegooijer.sbt/sbt-docker-label-schema/scala_2.10/sbt_0.13/...` part of the url path):

https://dl.bintray.com/rubendg/sbt-plugins/nl.rubendegooijer.sbt/sbt-docker-label-schema/scala_2.10/sbt_0.13/0.1.0/

but adding the default `bintrayRepo` resolver was fetching from a Maven pattern style of url (notice the `.../nl/rubendegooijer/sbt-docker-label-schema_2.10_0.13/...` part of the url path):

```scala    
// Bad
resolvers += Resolver.bintrayRepo("rubendg", "sbt-plugins")
addSbtPlugin("nl.rubendegooijer" % "sbt-docker-label-schema" % "0.1.0")

// Unresolved Dependencies -- tried url:
// https://dl.bintray.com/rubendg/sbt-plugins/nl/rubendegooijer/sbt-docker-label-schema_2.10_0.13/0.1.0/sbt-docker-label-schema-0.1.0.pom
```

Defining the resolver to follow Ivy patterns **and** also tweaking the `ModuleID` to `nl.rubendegooijer.sbt` made it work:

```scala
// Good
resolvers += Resolver.url("bintray-rubendg", url("https://dl.bintray.com/rubendg/sbt-plugins/"))(Resolver.ivyStylePatterns)
addSbtPlugin("nl.rubendegooijer.sbt" % "sbt-docker-label-schema" % "0.1.0")
```

Not sure if it is something specific of my setup or something worth updating in the **Usage Instructions**.

**Comment by rubendg** [comment]
Good point. Done here https://github.com/rubendg/sbt-docker-label-schema/commit/7b1328d92347eeffabf7be877d228219a263cfbe
